/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/Avatar/Avatar.vue')['default']
    Canvans: typeof import('./src/components/canvans/canvans.vue')['default']
    Comment: typeof import('./src/components/Comment/index.vue')['default']
    CommentList: typeof import('./src/components/CommentList/index.vue')['default']
    Content: typeof import('./src/components/Content/index.vue')['default']
    ContentValue: typeof import('./src/components/Content/details/contentValue/index.vue')['default']
    Details: typeof import('./src/components/Content/details/details.vue')['default']
    Enter: typeof import('./src/components/Enter/index.vue')['default']
    Err403: typeof import('./src/components/403/Err403.vue')['default']
    Err404: typeof import('./src/components/Error/Err404.vue')['default']
    Err500: typeof import('./src/components/500/Err500.vue')['default']
    Error: typeof import('./src/components/Error/Error.vue')['default']
    Footer: typeof import('./src/components/Footer/Footer.vue')['default']
    Head: typeof import('./src/components/Head/Head.vue')['default']
    Info: typeof import('./src/components/sideBar/Info.vue')['default']
    MessageBoard: typeof import('./src/components/MessageBoard/index.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NBackTop: typeof import('naive-ui')['NBackTop']
    NButton: typeof import('naive-ui')['NButton']
    NCalendar: typeof import('naive-ui')['NCalendar']
    NCard: typeof import('naive-ui')['NCard']
    NCarousel: typeof import('naive-ui')['NCarousel']
    NCode: typeof import('naive-ui')['NCode']
    NCollapse: typeof import('naive-ui')['NCollapse']
    NCollapseItem: typeof import('naive-ui')['NCollapseItem']
    NDivider: typeof import('naive-ui')['NDivider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NH3: typeof import('naive-ui')['NH3']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NList: typeof import('naive-ui')['NList']
    NListItem: typeof import('naive-ui')['NListItem']
    NPagination: typeof import('naive-ui')['NPagination']
    NSpace: typeof import('naive-ui')['NSpace']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTag: typeof import('naive-ui')['NTag']
    NThing: typeof import('naive-ui')['NThing']
    NUpload: typeof import('naive-ui')['NUpload']
    Pagination: typeof import('./src/components/Content/details/Pagination/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/SideBar/index.vue')['default']
    SlideShow: typeof import('./src/components/SlideShow/SlideShow.vue')['default']
    SvgComponent: typeof import('./src/components/svgComponent/index.vue')['default']
    TimeCard: typeof import('./src/components/TimeCard/index.vue')['default']
    Video: typeof import('./src/components/Video/index.vue')['default']
  }
}
